#!/bin/sh

# TODO: a complete rewrite, this file was first created like a year ago
#       this is the equivalent of corporate software that needs old code because no one knows how
#       or wants to modify it

file=""
wild=""

set_bg() {
	if [ ! -n "${bgdir+x}" ] ; then
		if [ -n "${BG_DIR+x}" ] ; then
			bgdir="$BG_DIR"
		else
			printf "No directory set\nUse -dir or set BG_DIR\n"
			exit 1
		fi
	fi

	printf "dir = $bgdir\n"
	if [ "$#" -gt 0 ] ; then
		wild="$1"
		file=$(find "$bgdir" -name "*$wild*" -type f | sort -R | head -n1)
		echo "wildcard = $wild"
	else
		file=$(find $bgdir -type f | sort -R | head -n1)
	fi
}

if [ "$1" = "-file" ] ; then
	file="$2"
elif [ "$1" = "-dir" ] ; then
	bgdir="$2"
	set_bg "$3"
else
	set_bg "$@"
fi

if [ -e "$file" ] ; then
	echo "file = $file"
	feh --no-fehbg --bg-max "$file"
else
	if [ -z "$file" ] ; then
		printf "No file found for wildcard: $wild\n"
	else
		printf "$file doesn't exist\n"
	fi
fi
